package:
  name: thrift_sasl
  version: "0.3.1"

source:
  fn: thrift_sasl-0.3.1.tar.gz
  url: ../dist/thrift_sasl-0.3.1.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sasl>=0.2.1
    - thrift>=0.10.0

  test:
      imports:
          - thrift_py

about:
  home: https://github.com/guillemborrell/thrift_sasl
  license: Apache License, Version 2.0
  license_family: Apache
  summary: Thrift SASL Python module
  description: Thrift SASL Python module
