package:
  name: thrift_sasl
  version: "0.3.1"

source:
  git_url: ../
  git_tag: v0.3.1


requirements:
  build:
    - python
    - setuptools

  run:
    - sasl>=0.2.1
    - thrift>=0.10.0

about:
  home: https://github.com/guillemborrell/thrift_sasl
  license: Apache License, Version 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Thrift SASL Python module
  description: Thrift SASL Python module
